version: '2'
services:
  db-data:
    container_name: db-data
    image: busybox
    volumes:
      - /data/db
  db:
    image: groonga/mroonga
    ports:
        - "3306:3306"
    expose:
      - 3306
    volumes_from:
      - db-data
  app:
    image: dotstamp_graphql:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
